the-via/qmk_userspace_via

keyboards/doio/kb09/keymaps/via/keymap.c
keyboards/doio/kb09/keymaps/via/rules.mk

Add kb09-01 layout
https://github.com/qmk/qmk_firmware/pull/24044

Add kb09-01 layout

---

keyboards/phdesign/phac/keymaps/via/keymap.c
keyboards/phdesign/phac/keymaps/via/rules.mk

Add VIA support for ph.design PH-AC rhythm game controller
https://github.com/qmk/qmk_firmware/pull/24368

Add VIA Support for PH-AC

---

keyboards/trnthsn/tyson60s/keymaps/via/keymap.c
keyboards/trnthsn/tyson60s/keymaps/via/rules.mk

- Add via layout support for tyson60s
[QMK pull request](https://github.com/qmk/qmk_firmware/pull/24047)

Add support for Tyson60s

---

keyboards/zeix/acidandco/stellaron/keymaps/via/keymap.c
keyboards/zeix/acidandco/stellaron/keymaps/via/rules.mk

Add support for Acid & Co's Stellaron. Checklist seems to have not been updated for merging of keymap instead of JSON, but I've ticked them in case of automated actions.
https://github.com/qmk/qmk_firmware/pull/24154

Add Acid & Co. Stellaron keymap

---

keyboards/zlabkeeb/vrynboard/keymaps/via/keymap.c
keyboards/zlabkeeb/vrynboard/keymaps/via/rules.mk

Add Keymaps  VRYNBOARD
https://github.com/qmk/qmk_firmware/pull/23931

Add Keymaps VIA VRYNBOARD

---

keyboards/jaykeeb/jk60rgb/keymaps/via/keymap.c
keyboards/jaykeeb/jk60rgb/keymaps/via/rules.mk

add support via keymap jk60 rgb
https://github.com/qmk/qmk_firmware/pull/24485

add jk60 rgb

---

keyboards/idyllic/pizzapad/keymaps/via/keymap.c
keyboards/idyllic/pizzapad/keymaps/via/rules.mk

As per title
https://github.com/qmk/qmk_firmware/pull/24566

Add Pizza Pad

---

keyboards/zeix/singa/kohaku/keymap.c
keyboards/zeix/singa/kohaku/rules.mk

Add SINGA Kohaku.
https://github.com/qmk/qmk_firmware/pull/24309

Add SINGA Kohaku

---

keyboards/zykrah/fuyu_hs/keymaps/via/config.h
keyboards/zykrah/fuyu_hs/keymaps/via/keymap.c
keyboards/zykrah/fuyu_hs/keymaps/via/rules.mk

Alternative PR for https://github.com/the-via/qmk_userspace_via/pull/21 to address some conflicts.
cc: @zykrah
https://github.com/qmk/qmk_firmware/pull/24567

Add FUYU HS

---

keyboards/druah/majestouch_redux/keymaps/via/keymap.c
keyboards/druah/majestouch_redux/keymaps/via/rules.mk

Title
https://github.com/qmk/qmk_firmware/pull/24586

Add Majestouch Redux

---

keyboards/deemen17/de80/keymaps/via/keymap.c
keyboards/deemen17/de80/keymaps/via/rules.mk

Add VIA keymap for DE80 PCB
https://github.com/qmk/qmk_firmware/pull/24439

Add VIA keymap for DE80

---

keyboards/cipulot/ec1_at/keymaps/via/config.h
keyboards/cipulot/ec1_at/keymaps/via/keymap.c
keyboards/cipulot/ec1_at/keymaps/via/rules.mk

Addition of EC1-AT
https://github.com/qmk/qmk_firmware/pull/24645

Addition of EC1-AT

---

keyboards/cipulot/ec_constellation/keymaps/via/keymap.c
keyboards/cipulot/ec_constellation/keymaps/via/rules.mk

Addition of EC Constellation
https://github.com/qmk/qmk_firmware/pull/24644

Addition of EC Constellation

---

keyboards/cipulot/ec_tkl_x/keymaps/via/config.h
keyboards/cipulot/ec_tkl_x/keymaps/via/keymap.c
keyboards/cipulot/ec_tkl_x/keymaps/via/rules.mk

Addition of EC TKL X
https://github.com/qmk/qmk_firmware/pull/24647

Addition of EC TKL X

---

keyboards/cipulot/ec_65x/keymaps/via/keymap.c
keyboards/cipulot/ec_65x/keymaps/via/rules.mk

Addition of EC65X
https://github.com/qmk/qmk_firmware/pull/24648

Addition of EC65X

---

keyboards/doio/kb38/keymaps/via/keymap.c
keyboards/doio/kb38/keymaps/via/rules.mk

Add kb38-01 keyboard
https://github.com/qmk/qmk_firmware/pull/23943
https://github.com/qmk/qmk_firmware/pull/23461
https://github.com/qmk/qmk_firmware/pull/21704
https://github.com/qmk/qmk_firmware/pull/21268
https://github.com/qmk/qmk_firmware/pull/19650

Add kb38-01 keyboard

---

keyboards/era/sirind/tomak79s/keymaps/via/keymap.c
keyboards/era/sirind/tomak79s/keymaps/via/rules.mk

Add SIRIND's Tomak79S
This is a solder version PCB for SIRIND's Tomak79 keyboard.
I would appreciate it if you would allow me to merge this into the VIA.
https://github.com/qmk/qmk_firmware/pull/24684

Add SIRIND's Tomak79S

---

keyboards/era/sirind/tomak79h/keymaps/via/keymap.c
keyboards/era/sirind/tomak79h/keymaps/via/rules.mk

Add SIRIND's Tomak79H
This is a hotswap version PCB for SIRIND's Tomak79 keyboard.
I would appreciate it if you would allow me to merge this into the VIA.
https://github.com/qmk/qmk_firmware/pull/24505

Add SIRIND's Tomak79H

---

keyboards/kradoindustries/promenade_rp24s/via/keymap.c
keyboards/kradoindustries/promenade_rp24s/via/rules.mk

Adding via keymap and via rules for Promenade RP24S
Adding Promenade RP24S for VIA support
[QMK RP#24689](https://github.com/qmk/qmk_firmware/pull/24689)

Adding New Keyboard Promenade RP24S

---

keyboards/a_jazz/akc084/keymaps/via/keymap.c
keyboards/a_jazz/akc084/keymaps/via/rules.mk

add a_jazz/akc084 via keymap
add a_jazz/akc084 via keymap
https://github.com/qmk/qmk_firmware/pull/24224

add a_jazz/akc084 via keymap

---

keyboards/ryanbaekr/rb87/keymaps/via_ryanbaekr/keymap.c
keyboards/ryanbaekr/rb87/keymaps/via_ryanbaekr/rules.mk

this keymap will ship on boards sold by the ryanbaekr etsy store
https://github.com/qmk/qmk_firmware/pull/19546
I think perhaps this checklist is for the via repo and not the userspace repo... leaving blank

new vendor keymap for rb87

---

keyboards/ibm/model_m/ctrl_m/keymaps/via/keymap.c
keyboards/ibm/model_m/ctrl_m/keymaps/via/rules.mk

Adding keyboard definition to the qmk_userspace_via for the ctrl-M replacement controller for IBM Model M keyboards.
Detailed description of the ctrl-M controller:
https://brain4free.org/wiki/doku.php/elektronik:ctrl_m
Link to merged QMK Pull Request:
https://github.com/qmk/qmk_firmware/pull/24375

Add ctrl_m

---

keyboards/swagkeys/eave/keymaps/via/keymap.c
keyboards/swagkeys/eave/keymaps/via/rules.mk
keyboards/swagkeys/integral/keymaps/via/keymap.c
keyboards/swagkeys/integral/keymaps/via/rules.mk

https://github.com/qmk/qmk_firmware/pull/24712
https://github.com/qmk/qmk_firmware/pull/24711

add swagkeys keymaps

---

keyboards/shuguet/shu89/keymaps/via/keymap.json

Adding a VIA compatible keymap to my new keyboard currently going through PR acceptance on QMK side.
https://github.com/qmk/qmk_firmware/pull/24758

Adding VIA keymap to keyboard shuguet/shu89

---

keyboards/clap_studio/flame60/keymaps/via/keymap.c
keyboards/clap_studio/flame60/keymaps/via/rules.mk

Preparation of _VIA_ support for the _Clap_Studio Flame 60%_ keyboard.
Link to the QMK pull request: https://github.com/qmk/qmk_firmware/pull/24870

Added the VIA keymap for the Clap_Studio/Flame60 keyboard

---

keyboards/keychron/c3_pro/ansi/red/keymaps/via/keymap.c
keyboards/keychron/c3_pro/ansi/red/keymaps/via/rules.mk
keyboards/keychron/c3_pro/ansi/rgb/keymaps/via/keymap.c
keyboards/keychron/c3_pro/ansi/rgb/keymaps/via/rules.mk

As title. Includes vendor code to work with [`keychron_common`](https://github.com/qmk/qmk_firmware/tree/master/keyboards/keychron/common) code as if the `keychron` keymap was also added. 
https://github.com/qmk/qmk_firmware/pull/24874

Add C3 Pro VIA keymaps (Redo)

---

keyboards/zykrah/fuyu/keymaps/via/keymap.c
keyboards/zykrah/fuyu_hs/keymaps/via/keymap.c

Fixed variable naming issue preventing compilation.

Fix Fuyu WS2812 RGB variable names

---

keyboards/suikagiken/suika15tone/keymaps/via/keymap.c
keyboards/suikagiken/suika15tone/keymaps/via/rules.mk

Add keyboard suika15tone.
https://github.com/qmk/qmk_firmware/pull/24947

add keyboard suika15tone

---

keyboards/mechboards/lily58/pro/keymaps/via/keymap.c
keyboards/mechboards/lily58/pro/keymaps/via/rules.mk

Add Mechboards Lily58.
https://github.com/qmk/qmk_firmware/pull/24937

Add Mechboards Lily58

---

keyboards/mechboards/sofle/pro/keymaps/via/keymap.c
keyboards/mechboards/sofle/pro/keymaps/via/rules.mk

Add Mechboards Sofle
qmk/qmk_firmware/pull/25004

Add Mechboards Sofle

---

keyboards/mechboards/crkbd/pro/keymaps/via/keymap.c
keyboards/mechboards/crkbd/pro/keymaps/via/rules.mk

Add Mechboards CRKBD.
https://github.com/qmk/qmk_firmware/pull/24993

Add Mechboards CRKBD

---

keyboards/keyten/kt60_mu/keymaps/via/keymap.c
keyboards/keyten/kt60_mu/keymaps/via/rules.mk

Add VIA keymap for keyten/kt60_MU
https://github.com/qmk/qmk_firmware/pull/24797

Add kt60-MU

---

keyboards/keychron/c2_pro_v2/ansi/rgb/keymaps/via/keymap.c
keyboards/keychron/c2_pro_v2/ansi/rgb/keymaps/via/rules.mk
keyboards/keychron/c2_pro_v2/ansi/white/keymaps/via/keymap.c
keyboards/keychron/c2_pro_v2/ansi/white/keymaps/via/rules.mk

As title. Same schtick as https://github.com/the-via/qmk_userspace_via/pull/61
https://github.com/qmk/qmk_firmware/pull/24900

Add Keychron C2 Pro V2 VIA keymaps

---

keyboards/keychron/c1_pro_v2/ansi/rgb/keymaps/via/keymap.c
keyboards/keychron/c1_pro_v2/ansi/rgb/keymaps/via/rules.mk
keyboards/keychron/c1_pro_v2/ansi/white/keymaps/via/keymap.c
keyboards/keychron/c1_pro_v2/ansi/white/keymaps/via/rules.mk

As title. Made in style of `keychron` keymap.
https://github.com/qmk/qmk_firmware/pull/24899

Add Keychron C1 Pro V2 VIA keymaps

---

keyboards/doio/kb38/keymaps/via/keymap.c

add `encoder_map` to allow firmware to compile
general cleanup of keymap
https://github.com/qmk/qmk_firmware/pull/19650

fixup kb38 keymap

---

keyboards/keyten/ortho_slayer/keymaps/via/keymap.c
keyboards/keyten/ortho_slayer/keymaps/via/rules.mk

Add VIA keymap for keyten/ortho_slayer
https://github.com/qmk/qmk_firmware/pull/25099

Add Ortho Slayer

---

keyboards/coban/pad12a/keymaps/via/keymap.c
keyboards/coban/pad12a/keymaps/via/rules.mk

- Add VIA support for Coban Pad 12A
https://github.com/qmk/qmk_firmware/pull/25039

Add Coban Pad 12A

---

keyboards/doio/kb38/keymaps/via/rules.mk

fixes missed item in #84 
(enable LTO to allow firmware to fit on MCU)
https://github.com/qmk/qmk_firmware/pull/19650

enable LTO for kb38

---

keyboards/xelus/valor/rev3/keymaps/via/keymap.c
keyboards/xelus/valor/rev3/keymaps/via/rules.mk

Add valor rev3
https://github.com/qmk/qmk_firmware/pull/22581/

add valor rev3

---

keyboards/ibm/model_m/modelh/keymaps/via/keymap.c
keyboards/ibm/model_m/modelh/keymaps/via/rules.mk

Adds via support for the modelh replacement board for IBM Model M keyboards.
https://modelh.club/
Source has already been in QMK master for a while now: https://github.com/qmk/qmk_firmware/pull/20625
Recent PR with some fixes to make this board support via (dynamic_keymap layer_count and acceptable vid): https://github.com/qmk/qmk_firmware/pull/24932

add modelh via keymap

---

keyboards/abko/ak84bt/keymaps/via/keymap.c
keyboards/abko/ak84bt/keymaps/via/rules.mk

https://github.com/qmk/qmk_firmware/pull/21243

Add ABKO ak84bt keyboard

---

keyboards/amptrics/0422/keymaps/via/keymap.c
keyboards/amptrics/0422/keymaps/via/rules.mk

Adding a VIA compatible keymap to my new keyboard currently going through PR acceptance on QMK side.
https://github.com/qmk/qmk_firmware/pull/24744

Amptrics 0420 via keyboard addition.

---

keyboards/salane/starryfrl/keymaps/via/keymap.c
keyboards/salane/starryfrl/keymaps/via/rules.mk

Adding via support for StarryFRL
https://github.com/qmk/qmk_firmware/pull/24626

add Starry FRL Support

---

keyboards/sneakbox/lilbae/keymaps/via/keymap.c
keyboards/sneakbox/lilbae/keymaps/via/rules.mk

Initial commit for VIA key layout for LilBAE macropad
https://github.com/qmk/qmk_firmware/pull/25259

initial commit lilbae keyboard layout

---

keyboards/dmqdesign/spin/keymaps/via/config.h
keyboards/dmqdesign/spin/keymaps/via/keymap.c
keyboards/dmqdesign/spin/keymaps/via/rules.mk

Added encoder support instead of being hard coded.
https://github.com/qmk/qmk_firmware/pull/12300

Switched SPIN macropad to encoder map

---

keyboards/keebio/foldkb/keymaps/via/keymap.c

Update keymap for FoldKB to add function keys and RGB matrix controls.
https://github.com/qmk/qmk_firmware/pull/21038

Update keymap for FoldKB

---

keyboards/sneakbox/lilbae/keymaps/via/keymap.c

multiple layout [QMK json](https://github.com/qmk/qmk_firmware/blob/master/keyboards/sneakbox/lilbae/keyboard.json#L36-L43), this keymap should use `LAYOUT_all` rather than `LAYOUT`
fix layout name, minor format nits
fixes the-via/qmk_userspace_via #98

fix lilbae layout name

---

keyboards/nulldesignco/null65ansi/v1/keymaps/via/keymap.c
keyboards/nulldesignco/null65ansi/v1/keymaps/via/rules.mk

Added null65ansi keyboard
https://github.com/qmk/qmk_firmware/pull/25464
Already merged to main: https://github.com/qmk/qmk_firmware/tree/master/keyboards/nulldesignco/null65ansi
I'm not sure if rgb matrix menus count as custom menus. Marking it just in case.

Add null65ansi VIA keymap
